# Generated by Django 5.1.5 on 2025-01-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_remove_message_user_chatlog_user_message_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='dateCreated',
            new_name='date_created',
        ),
    ]
