# Generated by Django 5.1.5 on 2025-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
